export const SCHEMA_VERSION = 1;

export const DocumentOrigin = Object.freeze({ SECOP: 'SECOP', USER_UPLOAD: 'USER_UPLOAD' });

export const DocumentRole = Object.freeze({
  CONTRACT: 'CONTRACT', PREVIOUS_STUDIES: 'PREVIOUS_STUDIES', TECHNICAL_ANNEX: 'TECHNICAL_ANNEX',
  TERMS: 'TERMS', PROPOSAL: 'PROPOSAL', START_ACT: 'START_ACT', SUPERVISION_REPORT: 'SUPERVISION_REPORT',
  PAYMENT: 'PAYMENT', INVOICE: 'INVOICE', DELIVERY_ACT: 'DELIVERY_ACT', MODIFICATION: 'MODIFICATION',
  ADDITION: 'ADDITION', EXTENSION: 'EXTENSION', SUSPENSION: 'SUSPENSION', RESTART: 'RESTART',
  GUARANTEE: 'GUARANTEE', LIQUIDATION: 'LIQUIDATION', OTHER: 'OTHER'
});

export const ExtractionStatus = Object.freeze({
  NOT_REQUESTED: 'NOT_REQUESTED', QUEUED: 'QUEUED', PROCESSING: 'PROCESSING', DONE: 'DONE', ERROR: 'ERROR'
});

export const AnalysisStatus = Object.freeze({
  NOT_ANALYZED: 'NOT_ANALYZED', INDEXED: 'INDEXED', ANALYZED: 'ANALYZED', REVIEW_REQUIRED: 'REVIEW_REQUIRED'
});

export const EvidenceStatus = Object.freeze({
  SIN_EVIDENCIA: 'SIN_EVIDENCIA', EVIDENCIA_LOCALIZADA: 'EVIDENCIA_LOCALIZADA',
  EVIDENCIA_PARCIAL: 'EVIDENCIA_PARCIAL', REVISADO: 'REVISADO', NO_APLICA: 'NO_APLICA'
});

export const Party = Object.freeze({
  CONTRACTOR: 'CONTRACTOR', ENTITY: 'ENTITY', SUPERVISOR: 'SUPERVISOR', OTHER: 'OTHER', UNDETERMINED: 'UNDETERMINED'
});
